#!/bin/sh

rm -rf $(realpath $1)/usr/lib/postgresql/10/include

git archive master | tar -x -C $(realpath $1)

for d in $(find $(realpath $1) -type d -name 'man[1-9]'); do
    for f in $(ls $d); do gzip $d/$f; done;
done

