#!/bin/sh

#if [ -e $1 ]; then
#    echo "Error:Could not export to $1, directory or file exsist.";
#    exit 1;
#fi

mkdir -p $1
git archive master | tar -x -C $1

for d in $(find $1 -type d -name 'man[1-9]'); do
    for f in $(ls $d); do gzip $d/$f; done;
done
