#!/bin/sh

set -e

VERSION=${DPKG_MAINTSCRIPT_PACKAGE##*-}

. /usr/share/postgresql-common/maintscripts-functions

stop_version $VERSION

if [ "$1" = remove ]; then
    remove_version $VERSION
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/postgresql" ] && [ "$1" = remove ]; then
	invoke-rc.d postgresql stop || exit $?
fi
# End automatically added section


if [ "$1" = remove ]; then
    remove_client_version $VERSION
fi
